### ISSUE TITLE
AuthTokenRetriever Not working (Help)

### ISSUE THREAD

**Issue by DonovanPhoenix** [sirkris/Reddit.NET#111]
I'm not sure what I'm doing wrong but I cannot get AuthTokenRetriever to work (I'm using VS 2019 com)

I have set the redirect URI to http://localhost:8080/Reddit.NET/oauthRedirect
I run the program, put in the app ID, it shows me the Reddit confirmation page,i accept then it crashes with this:

`Exception occured resolving a log provider. Logging for this assembly uhttpsharp, Version=0.1.5653.28566, Culture=neutral, PublicKeyToken=null is disabled. System.TypeInitializationException: The type initializer for 'uhttpsharp.Logging.LogProviders.ColouredConsoleLogProvider' threw an exception. ---> System.InvalidOperationException: System.Console or System.ConsoleColor type not found
   at uhttpsharp.Logging.LogProviders.ColouredConsoleLogProvider..cctor() in c:\Users\shani\Documents\GitHub\uHttpSharp\uhttpsharp\App_Packages\LibLog.3.1\LibLog.cs:line 1629
   --- End of inner exception stack trace ---
   at uhttpsharp.Logging.LogProviders.ColouredConsoleLogProvider.IsLoggerAvailable() in c:\Users\shani\Documents\GitHub\uHttpSharp\uhttpsharp\App_Packages\LibLog.3.1\LibLog.cs:line 1645
   at uhttpsharp.Logging.LogProvider.ResolveLogProvider() in c:\Users\shani\Documents\GitHub\uHttpSharp\uhttpsharp\App_Packages\LibLog.3.1\LibLog.cs:line 453
Exception occured resolving a log provider. Logging for this assembly uhttpsharp, Version=0.1.5653.28566, Culture=neutral, PublicKeyToken=null is disabled. System.TypeInitializationException: The type initializer for 'uhttpsharp.Logging.LogProviders.ColouredConsoleLogProvider' threw an exception. ---> System.InvalidOperationException: System.Console or System.ConsoleColor type not found
   at uhttpsharp.Logging.LogProviders.ColouredConsoleLogProvider..cctor() in c:\Users\shani\Documents\GitHub\uHttpSharp\uhttpsharp\App_Packages\LibLog.3.1\LibLog.cs:line 1629
   --- End of inner exception stack trace ---
   at uhttpsharp.Logging.LogProviders.ColouredConsoleLogProvider.IsLoggerAvailable() in c:\Users\shani\Documents\GitHub\uHttpSharp\uhttpsharp\App_Packages\LibLog.3.1\LibLog.cs:line 1645
   at uhttpsharp.Logging.LogProvider.ResolveLogProvider() in c:\Users\shani\Documents\GitHub\uHttpSharp\uhttpsharp\App_Packages\LibLog.3.1\LibLog.cs:line 453` 

The issue seems to come from **uHttpSharp** it also has this message:
`Package 'uHttpSharp 0.1.6.22' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project.`

Any help would be appreciated

**Comment by DonovanPhoenix** [comment]
I got it to work with this pull https://github.com/sirkris/Reddit.NET/pull/109

**Comment by sirkris** [comment]
This issue has been fixed by Issue #124.  Merged into 1.5.
